import { StyleSheet } from "react-native";

import { type ThemeColorPalette } from "@/constants/theme";

export const makeStyles = (c: ThemeColorPalette) =>
  StyleSheet.create({
    content: { padding: 20, paddingBottom: 36 },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    circle: {
      width: 42,
      height: 42,
      borderRadius: 15,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.surface,
      alignItems: "center",
      justifyContent: "center",
    },
    headerName: {
      color: c.foreground,
      maxWidth: 190,
      fontWeight: "800",
      fontSize: 15,
    },
    hero: {
      alignItems: "center",
      padding: 22,
      borderRadius: 28,
      marginTop: 20,
    },
    heroName: {
      color: c.foreground,
      fontFamily: "Georgia",
      fontSize: 27,
      marginTop: 17,
      textAlign: "center",
    },
    heroProgress: { fontSize: 12, fontWeight: "800", marginTop: 5 },
    amount: {
      color: c.foreground,
      fontSize: 38,
      lineHeight: 46,
      fontFamily: "Georgia",
      marginTop: 17,
      fontVariant: ["tabular-nums"],
    },
    of: { color: c.muted, fontSize: 13, marginTop: 2 },
    deadline: {
      flexDirection: "row",
      gap: 5,
      alignItems: "center",
      marginTop: 11,
    },
    deadlineText: { color: c.muted, fontSize: 11 },
    progressTrack: {
      alignSelf: "stretch",
      height: 6,
      borderRadius: 999,
      overflow: "hidden",
      backgroundColor: c.border,
      marginTop: 18,
    },
    progressFill: { height: "100%", borderRadius: 999 },
    remaining: { color: c.muted, fontSize: 12, marginTop: 9 },
    disabled: { opacity: 0.45 },
    actions: { flexDirection: "row", gap: 10, marginTop: 14 },
    deposit: {
      flex: 1,
      minHeight: 53,
      borderRadius: 17,
      backgroundColor: c.primary,
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      gap: 7,
    },
    depositText: { color: "#FFFDF9", fontSize: 14, fontWeight: "800" },
    withdraw: {
      flex: 1,
      minHeight: 53,
      borderRadius: 17,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.surface,
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      gap: 7,
    },
    withdrawText: { color: c.foreground, fontSize: 14, fontWeight: "800" },
    streak: {
      minHeight: 53,
      borderRadius: 17,
      marginTop: 13,
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 14,
      gap: 7,
    },
    streakText: { color: c.foreground, fontWeight: "800", fontSize: 13 },
    streakNote: { color: c.muted, marginLeft: "auto", fontSize: 11 },
    recurringCard: {
      borderRadius: 20,
      marginTop: 14,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.surface,
      padding: 15,
      flexDirection: "row",
      alignItems: "center",
      gap: 11,
    },
    recurringIcon: {
      width: 40,
      height: 40,
      borderRadius: 14,
      alignItems: "center",
      justifyContent: "center",
    },
    recurringLabel: {
      color: c.muted,
      letterSpacing: 0.9,
      fontWeight: "800",
      fontSize: 10,
    },
    recurringValue: {
      color: c.foreground,
      fontWeight: "800",
      fontSize: 14,
      marginTop: 3,
    },
    recurringNote: { color: c.muted, fontSize: 11, marginTop: 3 },
    editText: { fontSize: 12, fontWeight: "800" },
    buildHabit: {
      borderRadius: 20,
      marginTop: 14,
      borderWidth: 1,
      borderStyle: "dashed",
      borderColor: c.border,
      backgroundColor: c.surface,
      padding: 15,
      flexDirection: "row",
      alignItems: "center",
      gap: 11,
    },
    buildTitle: { color: c.foreground, fontWeight: "800", fontSize: 14 },
    buildCopy: { color: c.muted, fontSize: 12, marginTop: 3 },
    activityHeader: { marginTop: 27, marginBottom: 10 },
    activityTitle: { color: c.foreground, fontFamily: "Georgia", fontSize: 22 },
    activitySub: { color: c.muted, fontSize: 12, marginTop: 4 },
    entry: {
      minHeight: 65,
      flexDirection: "row",
      alignItems: "center",
      gap: 11,
    },
    entryIcon: {
      width: 39,
      height: 39,
      borderRadius: 13,
      alignItems: "center",
      justifyContent: "center",
    },
    entryTitle: { color: c.foreground, fontSize: 14, fontWeight: "800" },
    entryMeta: { color: c.muted, fontSize: 11, marginTop: 4 },
    entryAmount: {
      fontSize: 13,
      fontWeight: "800",
      fontVariant: ["tabular-nums"],
    },
    divider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: c.border,
      marginLeft: 51,
    },
    empty: { color: c.muted, fontSize: 13, paddingTop: 5, textAlign: "center" },
    backdrop: {
      flex: 1,
      justifyContent: "flex-end",
      backgroundColor: "rgba(32,27,24,.48)",
    },
    sheet: {
      backgroundColor: c.background,
      borderTopLeftRadius: 30,
      borderTopRightRadius: 30,
      padding: 23,
      paddingBottom: 32,
    },
    sheetHandle: {
      width: 41,
      height: 4,
      alignSelf: "center",
      borderRadius: 99,
      backgroundColor: c.border,
      marginBottom: 18,
    },
    sheetEyebrow: {
      color: c.muted,
      fontSize: 10,
      letterSpacing: 1.15,
      fontWeight: "800",
    },
    sheetTitle: {
      color: c.foreground,
      fontFamily: "Georgia",
      fontSize: 28,
      marginTop: 7,
    },
    sheetCopy: { color: c.muted, lineHeight: 20, fontSize: 13, marginTop: 7 },
    sheetAmount: {
      minHeight: 62,
      marginTop: 19,
      borderRadius: 17,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.surface,
      paddingHorizontal: 17,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    sheetCurrency: { color: c.primary, fontSize: 25, fontFamily: "Georgia" },
    sheetAmountInput: {
      flex: 1,
      color: c.foreground,
      fontSize: 27,
      fontFamily: "Georgia",
      fontVariant: ["tabular-nums"],
    },
    chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginTop: 15 },
    chip: {
      minHeight: 34,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.surface,
      paddingHorizontal: 13,
      paddingVertical: 6,
      alignItems: "flex-start",
      justifyContent: "center",
    },
    chipActive: { borderColor: c.border },
    chipText: { color: c.foreground, fontSize: 12, fontWeight: "800" },
    chipHint: {
      color: c.muted,
      fontSize: 10,
      fontWeight: "600",
      marginTop: 1,
      fontVariant: ["tabular-nums"],
    },
    previewBalance: {
      color: c.muted,
      fontSize: 12,
      marginTop: 8,
      fontVariant: ["tabular-nums"],
    },
    previewRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      marginTop: 8,
    },
    previewNewBalance: {
      color: c.foreground,
      fontSize: 12,
      fontWeight: "800",
      fontVariant: ["tabular-nums"],
    },
    previewPct: {
      fontSize: 12,
      fontWeight: "800",
      marginLeft: "auto",
      fontVariant: ["tabular-nums"],
    },
    statRow: { flexDirection: "row", gap: 10, marginTop: 14 },
    statCard: {
      flex: 1,
      borderRadius: 17,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.surface,
      paddingVertical: 13,
      paddingHorizontal: 14,
    },
    statLabel: {
      color: c.muted,
      fontSize: 10,
      letterSpacing: 1.1,
      fontWeight: "800",
    },
    statValue: {
      color: c.foreground,
      fontFamily: "Georgia",
      fontSize: 19,
      marginTop: 4,
      fontVariant: ["tabular-nums"],
    },
    noteInput: {
      minHeight: 49,
      marginTop: 10,
      borderRadius: 15,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.surface,
      paddingHorizontal: 14,
      color: c.foreground,
      fontSize: 13,
    },
    error: { color: c.error, minHeight: 18, fontSize: 11, marginTop: 6 },
    sheetButton: {
      minHeight: 53,
      borderRadius: 17,
      backgroundColor: c.primary,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 4,
    },
    sheetButtonText: { color: "#FFFDF9", fontWeight: "800", fontSize: 15 },
    cancel: { minHeight: 43, alignItems: "center", justifyContent: "center" },
    cancelText: { color: c.muted, fontWeight: "800", fontSize: 13 },
    pauseText: { color: c.warning, fontWeight: "800", fontSize: 13 },
    cadences: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginTop: 14 },
    cadence: {
      minHeight: 36,
      paddingHorizontal: 12,
      borderRadius: 11,
      borderWidth: 1,
      borderColor: c.border,
      justifyContent: "center",
      alignItems: "center",
    },
    cadenceText: { color: c.muted, fontSize: 11, fontWeight: "800" },
    cadenceTextActive: { color: "#FFFDF9" },
    celebrationBackdrop: {
      flex: 1,
      backgroundColor: "rgba(32,27,24,.58)",
      alignItems: "center",
      justifyContent: "center",
      padding: 24,
    },
    celebration: {
      width: "100%",
      maxWidth: 360,
      backgroundColor: c.surface,
      borderRadius: 30,
      padding: 24,
      alignItems: "center",
    },
    celebrationNumber: {
      color: c.primary,
      fontFamily: "Georgia",
      fontSize: 46,
      marginBottom: 6,
      fontVariant: ["tabular-nums"],
    },
    celebrationTitle: {
      color: c.foreground,
      fontFamily: "Georgia",
      fontSize: 27,
      marginTop: 17,
    },
    celebrationCopy: {
      color: c.muted,
      fontSize: 13,
      lineHeight: 20,
      textAlign: "center",
      marginTop: 9,
    },
    celebrationButton: {
      minHeight: 52,
      borderRadius: 17,
      backgroundColor: c.primary,
      alignSelf: "stretch",
      alignItems: "center",
      justifyContent: "center",
      marginTop: 21,
    },
    pressed: { opacity: 0.84, transform: [{ scale: 0.98 }] },
  });
