import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { useEffect, useMemo, useState } from "react";
import { Pressable, StyleSheet, Switch, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { type ThemeColorPalette } from "@/constants/theme";
import { useColors } from "@/hooks/use-colors";
import { useThemeContext } from "@/lib/theme-provider";

function Preference({ icon, title, detail, value, onChange, styles, colors }: { icon: string; title: string; detail: string; value: boolean; onChange: (next: boolean) => void; styles: ReturnType<typeof makeStyles>; colors: ThemeColorPalette }) {
  return <View style={styles.preference}><View style={styles.prefIcon}><MaterialIcons name={icon as never} size={19} color={colors.primary} /></View><View style={{ flex: 1 }}><Text style={styles.prefTitle}>{title}</Text><Text style={styles.prefDetail}>{detail}</Text></View><Switch value={value} onValueChange={onChange} trackColor={{ false: colors.border, true: `${colors.primary}8C` }} thumbColor={value ? colors.primary : "#FFFDF9"} /></View>;
}

export default function ProfileScreen() {
  const colors = useColors(); const styles = useMemo(() => makeStyles(colors), [colors]); const { appearanceMode, setAppearanceMode } = useThemeContext(); const [reminders, setReminders] = useState(false); const [appLock, setAppLock] = useState(false);
  useEffect(() => {
    AsyncStorage.multiGet(["saving-jar:reminders", "saving-jar:app-lock"]).then(([remindersPair, appLockPair]) => {
      if (remindersPair[1] !== null) setReminders(remindersPair[1] === "true");
      if (appLockPair[1] !== null) setAppLock(appLockPair[1] === "true");
    }).catch(() => undefined);
  }, []);
  const updateReminders = (next: boolean) => { setReminders(next); AsyncStorage.setItem("saving-jar:reminders", String(next)).catch(() => undefined); };
  const updateAppLock = (next: boolean) => { setAppLock(next); AsyncStorage.setItem("saving-jar:app-lock", String(next)).catch(() => undefined); };
  return <ScreenContainer className="p-5"><Text style={styles.kicker}>PROFILE</Text><Text style={styles.title}>Make it feel{`\n`}like yours.</Text><View style={styles.identity}><View style={styles.monogram}><Text style={styles.monogramText}>SJ</Text></View><View><Text style={styles.identityTitle}>Your Saving Jar</Text><Text style={styles.identityCopy}>A private progress tracker</Text></View></View><Text style={styles.sectionLabel}>APPEARANCE</Text><View style={styles.group}><Text style={styles.groupTitle}>Theme</Text><Text style={styles.groupCopy}>Choose the view that feels most comfortable.</Text><View style={styles.themes}>{(["light", "dark", "system"] as const).map((mode) => <Pressable key={mode} onPress={() => setAppearanceMode(mode)} style={({ pressed }) => [styles.themeChoice, appearanceMode === mode && styles.themeChoiceActive, pressed && styles.pressed]}><MaterialIcons name={(mode === "light" ? "light-mode" : mode === "dark" ? "dark-mode" : "brightness-auto") as never} size={17} color={appearanceMode === mode ? "#FFFDF9" : colors.muted} /><Text style={[styles.themeText, appearanceMode === mode && styles.themeTextActive]}>{mode === "system" ? "Auto" : mode[0].toUpperCase() + mode.slice(1)}</Text></Pressable>)}</View></View><Text style={styles.sectionLabel}>GENTLE SUPPORT</Text><View style={styles.group}><Preference icon="notifications-none" title="Saving reminders" detail="Nudges for the goals you choose" value={reminders} onChange={updateReminders} styles={styles} colors={colors} /><View style={styles.line} /><Preference icon="lock-outline" title="App lock" detail="Keep your jar details private" value={appLock} onChange={updateAppLock} styles={styles} colors={colors} /></View><Text style={styles.sectionLabel}>PREFERENCES</Text><View style={styles.currencyRow}><View style={styles.prefIcon}><MaterialIcons name="attach-money" size={19} color={colors.primary} /></View><View style={{ flex: 1 }}><Text style={styles.prefTitle}>Default currency</Text><Text style={styles.prefDetail}>Amounts are displayed in US dollars</Text></View><Text style={styles.currency}>USD</Text></View><View style={styles.about}><MaterialIcons name="favorite-border" size={18} color={colors.muted} /><Text style={styles.aboutText}>Saving Jar helps you track intent and progress. It does not transfer, hold, or invest your money.</Text></View></ScreenContainer>;
}

const makeStyles = (c: ThemeColorPalette) => StyleSheet.create({
  kicker: { color: c.muted, fontSize: 10, letterSpacing: 1.4, fontWeight: "800", marginTop: 4 }, title: { color: c.foreground, fontFamily: "Georgia", fontSize: 31, lineHeight: 36, marginTop: 7 }, identity: { minHeight: 82, marginTop: 23, backgroundColor: c.surface, borderColor: c.border, borderWidth: 1, borderRadius: 23, padding: 16, flexDirection: "row", alignItems: "center", gap: 13 }, monogram: { width: 48, height: 48, borderRadius: 17, backgroundColor: c.primary, alignItems: "center", justifyContent: "center" }, monogramText: { color: "#FFFDF9", fontFamily: "Georgia", fontSize: 16 }, identityTitle: { color: c.foreground, fontSize: 15, fontWeight: "800" }, identityCopy: { color: c.muted, fontSize: 12, marginTop: 4 }, sectionLabel: { color: c.muted, fontSize: 10, letterSpacing: 1.1, fontWeight: "800", marginTop: 26, marginBottom: 9 }, group: { borderRadius: 21, backgroundColor: c.surface, borderWidth: 1, borderColor: c.border, padding: 15 }, groupTitle: { color: c.foreground, fontSize: 14, fontWeight: "800" }, groupCopy: { color: c.muted, fontSize: 12, marginTop: 4 }, themes: { flexDirection: "row", gap: 7, marginTop: 14 }, themeChoice: { flex: 1, minHeight: 40, borderRadius: 12, borderWidth: 1, borderColor: c.border, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 5 }, themeChoiceActive: { backgroundColor: c.primary, borderColor: c.primary }, themeText: { color: c.muted, fontSize: 11, fontWeight: "800" }, themeTextActive: { color: "#FFFDF9" }, preference: { minHeight: 57, flexDirection: "row", alignItems: "center", gap: 11 }, prefIcon: { width: 37, height: 37, borderRadius: 13, backgroundColor: `${c.primary}12`, alignItems: "center", justifyContent: "center" }, prefTitle: { color: c.foreground, fontSize: 13, fontWeight: "800" }, prefDetail: { color: c.muted, fontSize: 11, marginTop: 3 }, line: { height: StyleSheet.hairlineWidth, backgroundColor: c.border, marginLeft: 48 }, currencyRow: { minHeight: 65, borderRadius: 20, backgroundColor: c.surface, borderColor: c.border, borderWidth: 1, paddingHorizontal: 15, flexDirection: "row", alignItems: "center", gap: 11 }, currency: { color: c.muted, fontSize: 11, fontWeight: "800", letterSpacing: .8 }, about: { flexDirection: "row", alignItems: "flex-start", gap: 9, marginTop: 24, paddingHorizontal: 10 }, aboutText: { color: c.muted, flex: 1, fontSize: 11, lineHeight: 17, textAlign: "left" }, pressed: { opacity: .84, transform: [{ scale: .98 }] },
});
